=== MrSkaprogramm/Computers-Sfia/src/main/resources/Devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="devices">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cpu">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element type="xs:double" name="price"/>
              <xs:element type="xs:int" name="energyConsumption"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:boolean" name="critical"/>
              <xs:element type="xs:double" name="clockRate"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="datastorage">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element type="xs:double" name="price"/>
              <xs:element type="xs:int" name="energyConsumption"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:boolean" name="critical"/>
              <xs:element type="xs:int" name="capacity"/>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="id"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="heatsink">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element type="xs:double" name="price"/>
              <xs:element type="xs:int" name="energyConsumption"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:boolean" name="critical"/>
              <xs:element type="xs:string" name="coolingType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="keyboard">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element type="xs:double" name="price"/>
              <xs:element type="xs:int" name="energyConsumption"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:boolean" name="critical"/>
              <xs:element type="xs:boolean" name="lights"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="motherboard">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element type="xs:double" name="price"/>
              <xs:element type="xs:int" name="energyConsumption"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:boolean" name="critical"/>
              <xs:element type="xs:string" name="formFactor"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="mouse">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element type="xs:double" name="price"/>
              <xs:element type="xs:int" name="energyConsumption"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:boolean" name="critical"/>
              <xs:element type="xs:byte" name="numOfButtons"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="powersupply">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element type="xs:double" name="price"/>
              <xs:element type="xs:int" name="energyConsumption"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:boolean" name="critical"/>
              <xs:element type="xs:int" name="powerRating"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ram">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element type="xs:double" name="price"/>
              <xs:element type="xs:int" name="energyConsumption"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:boolean" name="critical"/>
              <xs:element type="xs:string" name="RAMType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="screen">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element type="xs:double" name="price"/>
              <xs:element type="xs:int" name="energyConsumption"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:boolean" name="critical"/>
              <xs:element type="xs:int" name="size"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="speaker">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element type="xs:double" name="price"/>
              <xs:element type="xs:int" name="energyConsumption"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:boolean" name="critical"/>
              <xs:element type="xs:int" name="soundPower"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MrSkaprogramm/Computers-Sfia/src/main/resources/Devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Devices.xsd">
  <cpu>
    <origin>USA</origin>
    <price>300.0</price>
    <energyConsumption>75</energyConsumption>
    <type>MAIN</type>
    <critical>true</critical>
    <clockRate>3.0</clockRate>
  </cpu>
  <datastorage>
    <origin>China</origin>
    <price>50</price>
    <energyConsumption>3</energyConsumption>
    <type>MEMORY</type>
    <critical>true</critical>
    <capacity>1000</capacity>
  </datastorage>
  <heatsink>
    <origin>China</origin>
    <price>30</price>
    <energyConsumption>2</energyConsumption>
    <type>MAIN</type>
    <critical>true</critical>
    <coolingType>Air</coolingType>
  </heatsink>
  <keyboard>
    <origin>China</origin>
    <price>100</price>
    <energyConsumption>2</energyConsumption>
    <type>PERIPHERAL</type>
    <critical>false</critical>
    <lights>true</lights>
  </keyboard>
  <motherboard>
    <origin>China</origin>
    <price>180</price>
    <energyConsumption>0</energyConsumption>
    <type>MAIN</type>
    <critical>true</critical>
    <formFactor>ATX</formFactor>
  </motherboard>
  <mouse>
    <origin>China</origin>
    <price>60</price>
    <energyConsumption>2</energyConsumption>
    <type>PERIPHERAL</type>
    <critical>false</critical>
    <numOfButtons>5</numOfButtons>
  </mouse>
  <powersupply>
    <origin>Japan</origin>
    <price>140</price>
    <energyConsumption>0</energyConsumption>
    <type>MAIN</type>
    <critical>true</critical>
    <powerRating>1000</powerRating>
  </powersupply>
  <ram>
    <origin>Japan</origin>
    <price>100</price>
    <energyConsumption>2</energyConsumption>
    <type>MEMORY</type>
    <critical>true</critical>
    <RAMType>DDR5</RAMType>
  </ram>
  <screen>
    <origin>Korea</origin>
    <price>200</price>
    <energyConsumption>40</energyConsumption>
    <type>PERIPHERAL</type>
    <critical>false</critical>
    <size>30</size>
  </screen>
  <speaker>
    <origin>Canada</origin>
    <price>200</price>
    <energyConsumption>60</energyConsumption>
    <type>PERIPHERAL</type>
    <critical>false</critical>
    <soundPower>110</soundPower>
  </speaker>
</devices>
